apiVersion: v1
kind: ServiceAccount
metadata:
  {{- with .Values.serviceAccountAnnotations }}
  annotations:
    # kubernetes.io/enforce-mountable-secrets: "true"
    {{ toYaml . | nindent 4 }}
  {{- end }}
  name: {{ .Release.Name }}-sa
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}