name: "SkillSync infra deploy workflow"

on:
  push:
    branches:
      - main
permissions:
  id-token: write      


jobs:
  Plan-and-apply:
    name: "Clone repository, plan and apply  terraform"
    runs-on: ubuntu-latest
    steps:
      - name: "clone reposotory"
        uses: actions/checkout@v5
      - name: Authenticate with AWS OIDC
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-to-assume: ${{ secrets.ASSUME_ROLE }}
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.7"
      - name: Terraform initialize
        run: |
          aws sts get-caller-identity
          terraform init -backend-config="vars/ppe.backend.tfvars"
      - name: Terraform plan
        run: |
          terraform plan -var-file="vars/ppe.backend.tfvars" -out=tfpaln
      - name: Terraform apply
        run: |
          terraform apply -auto-approve tfplan   
           

