name: Terraform PR validate workflow

'on':
  pull_request:
    branches:
      - main

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  format-and-validate:
    name: format and validate terraform code
    runs-on: ubuntu-latest
    steps:
      - name: Clone code
        uses: actions/checkout@v5
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-to-assume: ${{ secrets.ASSUME_ROLE }}
      - name: Terraform format check
        run: |
          set e+
          terraform fmt -check -recursive
          if [ $? -eq 0 ]; then
            echo "✅ Format check passed."
          else
            echo "❌ Terraform code is not formated"
          fi
        shell: bash  
      - name: Validate Terraform configs
        run:
          set e+
          terraform validate -json > terraformValidation.json
          echo "check if terraform configuration is valid."
          isValid = jq '.valid' erraformValidation.json
          if [ $isValid == true ]; then
            echo "✅ Terraform config is valid."
          else
            echo "❌ Terraform validation failed."
          fi           
        shell: bash
          